[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Kimmo-RX-Numix
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Kimmo-RX-Numix
GtkTheme=Kimmo-RX-Numix
IconTheme=Kimmo-RX-Numix
MetacityTheme=Kimmo-RX-Numix
